### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by nabeken** [nabeken/delayd2#50]
```
2016/11/02 16:35:54 worker: receiving shutdown signal. waiting for the process finished.
2016/11/02 16:35:54 worker: resetting aborted messages remaining in active queue
panic: send on closed channel

goroutine 2283 [running]:
panic(0x868cc0, 0xc420b47fe0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/nabeken/delayd2.(*Worker).release(0xc4203d0370, 0x0, 0xc4202a3740)
        /go/src/github.com/nabeken/delayd2/worker.go:305 +0x217
github.com/nabeken/delayd2.(*Worker).releaseWorker(0xc4203d0370, 0xafd200, 0xc4203a0bc0)
        /go/src/github.com/nabeken/delayd2/worker.go:266 +0xfe
github.com/nabeken/delayd2.(*Worker).Run.func7()
        /go/src/github.com/nabeken/delayd2/worker.go:125 +0x3c
github.com/nabeken/delayd2.(*Worker).runWorker.func1(0xc42156cf20, 0xc4203d0370)
        /go/src/github.com/nabeken/delayd2/worker.go:73 +0x27
created by github.com/nabeken/delayd2.(*Worker).runWorker
        /go/src/github.com/nabeken/delayd2/worker.go:75 +0x66
```

And another error:

```
Unable to shutdown within 1m0s: context deadline exceeded
```

**Comment by nabeken** [comment]
closing as we no longer used channel.
